'use client';

import { useMemo, useState } from 'react';
import type {
    CompetitorTrendKpi,
    TrendDecisionSummary,
    TrendAction,
    EpicCompetitorRadar,
    RisingCategoryTrend,
    CompetitorDesignDna,
    CompetitorLaunchCalendarItem,
    CompetitorGapAnalysisItem,
    TrendPlanningRecommendation,
    CompetitorMaterialItem,
    CompetitorTrendRelatedModuleLink,
    CompetitorTrendFilters,
} from '@/types/competitorTrendTypes';

// ─── Mock KPI Data ───────────────────────────────────────────────────────────
const MOCK_KPIS: CompetitorTrendKpi[] = [
    {
        id: 'monitored_brands',
        label: '监控竞品品牌数',
        value: 8,
        unit: '个',
        delta: '+1',
        deltaType: 'mom',
        deltaPositive: true,
        statusColor: 'blue',
        explanation: '本月新增 Hoka 监控覆盖，共覆盖 8 个主要竞品',
    },
    {
        id: 'monitored_series',
        label: '监控系列数',
        value: 42,
        unit: '个',
        delta: '+5',
        deltaType: 'mom',
        deltaPositive: true,
        statusColor: 'blue',
        explanation: '共跟踪 42 个竞品系列，涵盖主力跑鞋/休闲/训练品类',
    },
    {
        id: 'hot_trends',
        label: '高热趋势数',
        value: 7,
        unit: '个',
        delta: '+2',
        deltaType: 'mom',
        deltaPositive: true,
        statusColor: 'green',
        explanation: '7 个趋势热度分 >80，其中老爹鞋/厚底2个处于爆发期',
    },
    {
        id: 'price_band_opportunities',
        label: '价格带机会数',
        value: 3,
        unit: '个',
        delta: '',
        statusColor: 'green',
        explanation: '299-399 / 499-599 / 699-799 三个价格带存在明显机会窗口',
    },
    {
        id: 'rising_categories',
        label: '升量品类数',
        value: 5,
        unit: '个',
        delta: '+1',
        deltaType: 'mom',
        deltaPositive: true,
        statusColor: 'blue',
        explanation: '跑步/户外/训练/休闲/篮球 5 个品类 SKU 和热度双升',
    },
    {
        id: 'design_opportunities',
        label: '设计机会数',
        value: 6,
        unit: '个',
        delta: '',
        statusColor: 'purple',
        explanation: '6 个竞品设计语言已进入设计灵感池待提案',
    },
    {
        id: 'risk_trends',
        label: '风险趋势数',
        value: 2,
        unit: '个',
        delta: '+1',
        deltaType: 'mom',
        deltaPositive: false,
        statusColor: 'red',
        explanation: '奢华厚底和联名限定出现跟风过热风险，建议暂缓',
    },
    {
        id: 'enter_planning',
        label: '建议进入企划数',
        value: 4,
        unit: '个',
        delta: '',
        statusColor: 'green',
        explanation: '4 个趋势已满足进入 W3/W4 波段企划的条件',
    },
];

// ─── Mock Trend Decision Summary ─────────────────────────────────────────────
const MOCK_DECISION_SUMMARY: TrendDecisionSummary = {
    followTrends: [
        '厚底老爹鞋（增长率 +38%，热度持续上升）',
        '户外越野跑（轻量化材质 + 防滑大底，竞品 SKU 快速增加）',
        '功能性跑步（碳板/氮科技，已进入大众市场）',
    ],
    avoidTrends: [
        '奢华限定联名（溢价空间被压缩，复购率低）',
        '纯时尚厚底（市场已饱和，头部品牌 SKU 高度重叠）',
    ],
    bestPriceBand: '399-599元（竞品热度最高，本品 SKU 空缺明显）',
    bestCategoryStyle: '跑步-轻量竞速 / 休闲-厚底老爹鞋',
    enterDesignPlan: ['厚底老爹鞋廓形语言', '户外越野功能细节', '碳板跑步视觉系统'],
    enterWavePlan: ['W3 春夏厚底老爹系列', 'W4 夏季轻量跑步系列'],
    smallBatchTest: ['荧光色涂层工艺（颜色故事趋势）', '再生材料鞋面（可持续功能卖点）'],
};

// ─── Mock Trend Actions ───────────────────────────────────────────────────────
const MOCK_ACTIONS: TrendAction[] = [
    {
        id: 'action_001',
        trendObject: '厚底老爹鞋 / 399-599 / 休闲',
        trendTag: '高热',
        trendEvidence: '竞品 New Balance 990v6 在 399-599 价格带热度分 92，SKU+15%，小红书种草量月增 40%',
        recommendedAction: '加入波段企划',
        targetAudience: '18-28岁潮流女性 / 泛运动生活场景',
        recommendedCategory: '休闲鞋',
        recommendedShoeType: '厚底老爹鞋',
        recommendedPriceBand: '399-599',
        recommendedWaveId: 'W3',
        expectedSalesImpact: '+120-180万元',
        expectedMarginImpact: '+2.1pp 毛利率',
        actionStatus: 'pending',
        priority: 1,
    },
    {
        id: 'action_002',
        trendObject: '户外越野跑 / 599-799 / 跑步',
        trendTag: '升量',
        trendEvidence: 'Salomon / Hoka 在 599-799 户外跑步 SKU 同比+28%，热度连续3月上升',
        recommendedAction: '生成趋势Brief',
        targetAudience: '25-40岁都市轻户外人群',
        recommendedCategory: '跑步鞋',
        recommendedShoeType: '越野跑鞋',
        recommendedPriceBand: '599-799',
        recommendedWaveId: 'W4',
        expectedSalesImpact: '+80-120万元',
        expectedMarginImpact: '+3.2pp 毛利率',
        actionStatus: 'pending',
        priority: 2,
    },
    {
        id: 'action_003',
        trendObject: '碳板跑步 / 799+ / 竞速跑',
        trendTag: '设计机会',
        trendEvidence: 'Nike Vaporfly / Adidas Adizero 碳板系列连续热卖，竞品均价上移至 899 元',
        recommendedAction: '生成竞品对标Brief',
        targetAudience: '30-45岁跑者 / 马拉松爱好者',
        recommendedCategory: '跑步鞋',
        recommendedShoeType: '竞速跑鞋',
        recommendedPriceBand: '799+',
        recommendedWaveId: 'W3',
        expectedSalesImpact: '+60-90万元',
        expectedMarginImpact: '+4.5pp 毛利率',
        actionStatus: 'in_progress',
        priority: 3,
    },
    {
        id: 'action_004',
        trendObject: '荧光色涂层 / 颜色趋势',
        trendTag: '小批量测试',
        trendEvidence: '竞品荧光色 SKU 热度分上升至 74，但 SKU 数量少，市场接受度未验证',
        recommendedAction: '小批量测试',
        targetAudience: '20-30岁个性运动人群',
        recommendedCategory: '跑步/休闲',
        recommendedShoeType: '多品类通用',
        recommendedPriceBand: '299-499',
        recommendedWaveId: 'W3',
        expectedSalesImpact: '+20-40万元（测试规模）',
        expectedMarginImpact: '待验证',
        actionStatus: 'pending',
        priority: 4,
    },
    {
        id: 'action_005',
        trendObject: '奢华联名限定',
        trendTag: '避免跟进',
        trendEvidence: '竞品限定联名热度虚高，复购率仅 12%，溢价消费者占比不足 5%',
        recommendedAction: '避免跟进',
        targetAudience: '潮流收藏人群（非核心受众）',
        recommendedCategory: '休闲鞋',
        recommendedShoeType: '低帮休闲鞋',
        recommendedPriceBand: '999+',
        recommendedWaveId: '-',
        expectedSalesImpact: '风险 > 机会',
        expectedMarginImpact: '-3.2pp（折扣处理风险）',
        actionStatus: 'rejected',
        priority: 5,
    },
    {
        id: 'action_006',
        trendObject: '再生材料鞋面 / 可持续功能',
        trendTag: '设计机会',
        trendEvidence: 'Allbirds / On 可持续材料系列在一二线城市热度上升，Z世代消费者偏好强',
        recommendedAction: '加入设计灵感池',
        targetAudience: 'Z世代 / 环保消费者',
        recommendedCategory: '跑步/休闲',
        recommendedShoeType: '低帮休闲/轻量跑',
        recommendedPriceBand: '499-699',
        recommendedWaveId: 'W4',
        expectedSalesImpact: '+30-60万元',
        expectedMarginImpact: '+1.8pp 毛利率',
        actionStatus: 'pending',
        priority: 6,
    },
];

// ─── Mock EPIC Radar ─────────────────────────────────────────────────────────
const MOCK_EPIC_RADARS: EpicCompetitorRadar[] = [
    {
        id: 'epic_001',
        competitorBrand: 'Nike',
        competitorSeries: 'Air Max 2025',
        epicEmotionScore: 92,
        epicProductScore: 88,
        epicInfluenceScore: 95,
        epicCommercialScore: 85,
        epicTotalScore: 90,
        strengths: ['视觉吸引力极强', '社媒影响力第一', '品类渗透率高'],
        weaknesses: ['价格偏高', '性价比感知弱'],
        learnable: ['廓形语言', '颜色故事系统', '社媒种草节奏'],
        riskPoints: ['直接对标会陷入价格战'],
    },
    {
        id: 'epic_002',
        competitorBrand: 'New Balance',
        competitorSeries: '990v6',
        epicEmotionScore: 82,
        epicProductScore: 90,
        epicInfluenceScore: 78,
        epicCommercialScore: 88,
        epicTotalScore: 85,
        strengths: ['产品工艺口碑强', '价格带运营成熟', '老爹鞋品类话语权'],
        weaknesses: ['视觉创新偏弱', '年轻化渗透不足'],
        learnable: ['价格带分层策略', '工艺细节展示方式', '核心用户运营'],
        riskPoints: ['老爹鞋市场进入红海区'],
    },
    {
        id: 'epic_003',
        competitorBrand: 'Hoka',
        competitorSeries: 'Clifton 9',
        epicEmotionScore: 75,
        epicProductScore: 95,
        epicInfluenceScore: 72,
        epicCommercialScore: 80,
        epicTotalScore: 81,
        strengths: ['功能卖点突出', '大底科技壁垒高', '专业跑者口碑'],
        weaknesses: ['时尚感偏弱', '颜色故事单调'],
        learnable: ['功能卖点提炼方式', '专业跑者沟通策略'],
        riskPoints: ['专业运动市场进入壁垒高'],
    },
    {
        id: 'epic_004',
        competitorBrand: 'Salomon',
        competitorSeries: 'XT-6',
        epicEmotionScore: 88,
        epicProductScore: 92,
        epicInfluenceScore: 85,
        epicCommercialScore: 76,
        epicTotalScore: 86,
        strengths: ['户外功能性极强', '视觉差异化明显', '潮流圈渗透成功'],
        weaknesses: ['价格偏高', '渠道覆盖有限'],
        learnable: ['功能与时尚融合设计', '户外越野视觉语言'],
        riskPoints: ['定价策略复制难度大'],
    },
];

// ─── Mock Rising Category Trends ─────────────────────────────────────────────
const MOCK_RISING_TRENDS: RisingCategoryTrend[] = [
    {
        id: 'rising_001',
        category: '跑步鞋',
        shoeType: '越野跑鞋',
        growthRate: 34,
        heatChange: +18,
        skuChange: +22,
        priceBand: '599-799',
        competitorBrands: ['Salomon', 'Hoka', 'Merrell'],
        fitForBrand: true,
        recommendedAction: '加入波段企划',
        statusColor: 'green',
    },
    {
        id: 'rising_002',
        category: '休闲鞋',
        shoeType: '厚底老爹鞋',
        growthRate: 38,
        heatChange: +24,
        skuChange: +31,
        priceBand: '399-599',
        competitorBrands: ['New Balance', 'Asics', 'Brooks'],
        fitForBrand: true,
        recommendedAction: '加入波段企划',
        statusColor: 'green',
    },
    {
        id: 'rising_003',
        category: '跑步鞋',
        shoeType: '碳板竞速跑',
        growthRate: 28,
        heatChange: +15,
        skuChange: +12,
        priceBand: '799+',
        competitorBrands: ['Nike', 'Adidas', 'New Balance'],
        fitForBrand: false,
        recommendedAction: '观察一轮',
        statusColor: 'orange',
    },
    {
        id: 'rising_004',
        category: '训练鞋',
        shoeType: '综合训练鞋',
        growthRate: 19,
        heatChange: +9,
        skuChange: +8,
        priceBand: '399-599',
        competitorBrands: ['Nike', 'Reebok', 'Under Armour'],
        fitForBrand: true,
        recommendedAction: '小批量测试',
        statusColor: 'blue',
    },
    {
        id: 'rising_005',
        category: '休闲鞋',
        shoeType: '板鞋',
        growthRate: 12,
        heatChange: +5,
        skuChange: +4,
        priceBand: '299-499',
        competitorBrands: ['Vans', 'Converse', 'DC'],
        fitForBrand: true,
        recommendedAction: '观察一轮',
        statusColor: 'blue',
    },
];

// ─── Mock Design DNA ──────────────────────────────────────────────────────────
const MOCK_DESIGN_DNA: CompetitorDesignDna[] = [
    {
        id: 'dna_001',
        competitorBrand: 'New Balance',
        competitorSeries: '990v6',
        shoeType: '厚底老爹鞋',
        silhouette: '宽胖圆润廓形，低调复古感',
        lastShape: '宽楦，前掌放松，不挤脚',
        soleStructure: 'ABZORB+ENCAP 双层缓震底，厚度约 32mm',
        upperMaterial: '猪皮 + 网布混合，质感丰富',
        colorStory: '灰/米/绿大地色系，低饱和度为主',
        craftDetail: '皮革拼接缝线、反光条点缀',
        functionKeypoint: '全天候缓震、宽楦稳定支撑',
        visualKeywords: ['复古', '厚底', '大地色', '工装感'],
        learnable: ['宽楦设计提升舒适感认知', '低饱和色系降低搭配门槛', '双层大底工艺展示'],
        avoidPoints: ['直接抄袭廓形比例', '同款配色竞争'],
    },
    {
        id: 'dna_002',
        competitorBrand: 'Salomon',
        competitorSeries: 'XT-6',
        shoeType: '户外越野跑鞋',
        silhouette: '机能感强，高包裹性鞋帮',
        lastShape: '标准楦型，前掌略宽',
        soleStructure: 'Contagrip 外底 + 全长 EVA 中底，防穿刺设计',
        upperMaterial: 'TPU 骨架 + 工业织物，耐磨耐刮',
        colorStory: '电光蓝/荧光绿/警示橙，高识别度配色',
        craftDetail: '快穿鞋带系统（Quicklace），鞋领 EVA 锁定',
        functionKeypoint: '防穿刺、防滑、全地形抓地',
        visualKeywords: ['机能', '户外', '高识别度', '科技感'],
        learnable: ['快穿系统差异化卖点', '功能性外观设计语言', '高识别配色抢眼效果'],
        avoidPoints: ['完全复制机能感外观（定位冲突）'],
    },
    {
        id: 'dna_003',
        competitorBrand: 'Hoka',
        competitorSeries: 'Clifton 9',
        shoeType: '厚底公路跑鞋',
        silhouette: '超厚中底 + 流线型鞋帮，偏中性',
        lastShape: '宽楦，前掌活动空间大',
        soleStructure: '全长 CMEVA 超厚中底，约 38mm，主动缓震',
        upperMaterial: '轻量单层工程网布，透气极佳',
        colorStory: '糖果色系为主，高对比撞色中底',
        craftDetail: '超薄橡胶外底局部覆盖，中底外露',
        functionKeypoint: '超轻缓震、减轻下肢疲劳感',
        visualKeywords: ['厚底', '轻量', '糖果色', '减震科技'],
        learnable: ['超厚中底视觉差异化', '轻量化网布鞋面工艺', '撞色中底设计语言'],
        avoidPoints: ['大底工艺有专利壁垒，不建议直接复制'],
    },
];

// ─── Mock Launch Calendar ─────────────────────────────────────────────────────
const MOCK_LAUNCH_CALENDAR: CompetitorLaunchCalendarItem[] = [
    {
        id: 'cal_001',
        competitorBrand: 'Nike',
        competitorSeries: 'Air Max 2025 春季',
        launchMonth: 3,
        launchWave: 'W2',
        mainCategory: '休闲鞋',
        priceBand: '599-799',
        skuCount: 12,
        mainChannel: '电商+直营',
        discountTiming: '上市后 8 周打折',
        heatChange: +32,
        impactOnOurBrand: '休闲鞋 399-599 价格带流量可能分流',
        suggestedResponse: '加入波段企划',
    },
    {
        id: 'cal_002',
        competitorBrand: 'New Balance',
        competitorSeries: '990v6 春夏色系',
        launchMonth: 4,
        launchWave: 'W3',
        mainCategory: '休闲鞋',
        priceBand: '399-599',
        skuCount: 8,
        mainChannel: '电商',
        discountTiming: '上市后 6 周节点促销',
        heatChange: +24,
        impactOnOurBrand: '老爹鞋价格带直接竞争',
        suggestedResponse: '生成竞品对标Brief',
    },
    {
        id: 'cal_003',
        competitorBrand: 'Salomon',
        competitorSeries: 'XT-6 夏季户外',
        launchMonth: 5,
        launchWave: 'W4',
        mainCategory: '跑步鞋',
        priceBand: '699-899',
        skuCount: 6,
        mainChannel: '直营+专业跑步店',
        discountTiming: '全年不折扣策略',
        heatChange: +18,
        impactOnOurBrand: '户外越野跑品类教育竞争',
        suggestedResponse: '观察一轮',
    },
    {
        id: 'cal_004',
        competitorBrand: 'Hoka',
        competitorSeries: 'Clifton 9 夏季轻量版',
        launchMonth: 5,
        launchWave: 'W4',
        mainCategory: '跑步鞋',
        priceBand: '599-799',
        skuCount: 10,
        mainChannel: '电商+直营',
        discountTiming: '上市后 12 周双11节点',
        heatChange: +20,
        impactOnOurBrand: '功能跑鞋科技感比较中处于劣势',
        suggestedResponse: '调整品类结构',
    },
];

// ─── Mock Gap Analysis ────────────────────────────────────────────────────────
const MOCK_GAP_ANALYSIS: CompetitorGapAnalysisItem[] = [
    {
        id: 'gap_001',
        dimension: '价格带',
        competitorPerformance: '399-599 区间 Top3 竞品均有 8-15 款核心 SKU',
        ourPerformance: '同价格带仅 4 款',
        gap: '缺口约 6-11 款',
        impact: '竞争失位，流量和份额持续流失',
        recommendedAction: '加入波段企划',
        relatedModule: '波段企划 / OTB',
        riskLevel: 'high',
    },
    {
        id: 'gap_002',
        dimension: 'SKU数量',
        competitorPerformance: '主要竞品在跑步鞋品类平均 SKU 22 款',
        ourPerformance: '本品跑步鞋 SKU 14 款',
        gap: '-8 款',
        impact: '品类话语权不足，消费者选择空间受限',
        recommendedAction: '调整品类结构',
        relatedModule: '品类运营',
        riskLevel: 'medium',
    },
    {
        id: 'gap_003',
        dimension: '鞋型',
        competitorPerformance: '厚底老爹鞋品类竞品覆盖率 95%+',
        ourPerformance: '本品无厚底老爹鞋 SKU',
        gap: '品类缺失',
        impact: '休闲鞋增量市场完全缺失',
        recommendedAction: '生成趋势Brief',
        relatedModule: '设计计划 / 波段企划',
        riskLevel: 'high',
    },
    {
        id: 'gap_004',
        dimension: '社媒热度',
        competitorPerformance: 'Nike/NB 月均小红书笔记 5000+ 篇，热度分 90+',
        ourPerformance: '本品月均 800 篇，热度分 62',
        gap: '热度差距 -28 分',
        impact: '新品认知爬坡慢，动销依赖折扣',
        recommendedAction: '观察一轮',
        relatedModule: '消费者画像 / 销售预测',
        riskLevel: 'medium',
    },
    {
        id: 'gap_005',
        dimension: '上市节奏',
        competitorPerformance: '竞品 3 月 / 5 月双波次主推，抢占春夏流量高峰',
        ourPerformance: '本品 4 月单波次，错过 3 月流量',
        gap: '节奏滞后 4-6 周',
        impact: '错失春季流量高峰，依赖折扣清货',
        recommendedAction: '加入波段企划',
        relatedModule: '波段企划',
        riskLevel: 'medium',
    },
    {
        id: 'gap_006',
        dimension: '功能卖点',
        competitorPerformance: 'Hoka 碳板+超厚缓震，Salomon 防穿刺+全地形',
        ourPerformance: '本品主要强调轻量化，无差异化科技卖点',
        gap: '科技卖点话语权缺失',
        impact: '高价格带购买理由不充分，均价受限',
        recommendedAction: '生成竞品对标Brief',
        relatedModule: '设计计划',
        riskLevel: 'high',
    },
];

// ─── Mock Planning Recommendations ───────────────────────────────────────────
const MOCK_PLANNING_RECS: TrendPlanningRecommendation[] = [
    {
        trendId: 'trend_001',
        trendName: '厚底老爹鞋-大地色系',
        trendEvidence: 'New Balance 990v6 热度 92，连续 4 个月 SKU+，小红书搜索量 +65%',
        fitCategory: '休闲鞋',
        fitShoeType: '厚底老爹鞋',
        recommendedPriceBand: '399-599',
        recommendedSkuCount: 6,
        recommendedWaveId: 'W3',
        recommendedChannel: '电商+直营',
        designSuggestion: '参考宽楦廓形，开发灰/米/橄榄低饱和配色，工装风格细节点缀',
        otbImpact: '建议 OTB 投放 80-120 万，首批 SKU 3 款，验证后追加',
        riskLevel: 'low',
        recommendedAction: '加入波段企划',
        statusColor: 'green',
    },
    {
        trendId: 'trend_002',
        trendName: '户外越野跑-轻量机能',
        trendEvidence: 'Salomon XT-6 / Hoka Speedgoat 在一线城市热度持续攀升，增长率 +34%',
        fitCategory: '跑步鞋',
        fitShoeType: '越野跑鞋',
        recommendedPriceBand: '599-799',
        recommendedSkuCount: 4,
        recommendedWaveId: 'W4',
        recommendedChannel: '电商+专业门店',
        designSuggestion: '引入机能感外观语言，快穿系统，高识别度配色，前掌防刺穿设计',
        otbImpact: '建议 OTB 60-80 万，首批测试款 2 款，验证市场认知后扩款',
        riskLevel: 'medium',
        recommendedAction: '生成趋势Brief',
        statusColor: 'blue',
    },
    {
        trendId: 'trend_003',
        trendName: '功能性训练-综合训练鞋',
        trendEvidence: 'Nike Metcon / Reebok Nano 综合训练热度分 78，健身房场景渗透率+19%',
        fitCategory: '训练鞋',
        fitShoeType: '综合训练鞋',
        recommendedPriceBand: '399-599',
        recommendedSkuCount: 3,
        recommendedWaveId: 'W3',
        recommendedChannel: '电商',
        designSuggestion: '强化大底稳定性展示，前掌宽楦，鞋帮高支撑，中性色系为主',
        otbImpact: '建议小批量 OTB 30-50 万，主要用于测试',
        riskLevel: 'medium',
        recommendedAction: '小批量测试',
        statusColor: 'orange',
    },
    {
        trendId: 'trend_004',
        trendName: '碳板竞速跑-高端跑者',
        trendEvidence: 'Nike Vaporfly / Adidas Adizero 碳板系列热度分 88，但价格带 799+ 本品无布局',
        fitCategory: '跑步鞋',
        fitShoeType: '竞速跑鞋',
        recommendedPriceBand: '799+',
        recommendedSkuCount: 2,
        recommendedWaveId: 'W4',
        recommendedChannel: '直营+专业店',
        designSuggestion: '碳板外露设计、轻量单层网布鞋面、专业配色，重点强调克重卖点',
        otbImpact: '建议 OTB 40-60 万，首期少量但需足够库深维持专业形象',
        riskLevel: 'high',
        recommendedAction: '观察一轮',
        statusColor: 'orange',
    },
];

// ─── Mock Material Gallery ────────────────────────────────────────────────────
const MOCK_MATERIALS: CompetitorMaterialItem[] = [
    {
        id: 'mat_001',
        imageUrl: '/assets/gallery/comp_nb_990.jpg',
        competitorBrand: 'New Balance',
        competitorSeries: '990v6',
        year: 2026,
        season: 'SS',
        category: '休闲鞋',
        shoeType: '厚底老爹鞋',
        price: 499,
        heatScore: 92,
        tags: ['厚底', '大地色', '复古', '高热'],
        materialCategory: '高热趋势',
        learnable: '宽楦廓形设计，低饱和配色系统，皮料质感展示',
        statusColor: 'green',
    },
    {
        id: 'mat_002',
        imageUrl: '/assets/gallery/comp_salomon_xt6.jpg',
        competitorBrand: 'Salomon',
        competitorSeries: 'XT-6',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '越野跑鞋',
        price: 799,
        heatScore: 88,
        tags: ['机能', '户外', '越野', '设计机会'],
        materialCategory: '设计参考',
        learnable: '快穿系统、机能外观语言、高对比色系',
        statusColor: 'blue',
    },
    {
        id: 'mat_003',
        imageUrl: '/assets/gallery/comp_hoka_clifton9.jpg',
        competitorBrand: 'Hoka',
        competitorSeries: 'Clifton 9',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '厚底公路跑',
        price: 699,
        heatScore: 85,
        tags: ['厚底', '缓震', '糖果色', '轻量'],
        materialCategory: '设计参考',
        learnable: '超厚中底撞色处理，轻量网布展示方式',
        statusColor: 'blue',
    },
    {
        id: 'mat_004',
        imageUrl: '/assets/gallery/comp_nike_airmax.jpg',
        competitorBrand: 'Nike',
        competitorSeries: 'Air Max 2025',
        year: 2026,
        season: 'SS',
        category: '休闲鞋',
        shoeType: '气垫休闲鞋',
        price: 699,
        heatScore: 90,
        tags: ['气垫', '高热', '价格带机会'],
        materialCategory: '价格带机会',
        learnable: '气垫视窗展示，街拍场景氛围',
        statusColor: 'green',
    },
    {
        id: 'mat_005',
        imageUrl: '/assets/gallery/comp_adidas_ultra.jpg',
        competitorBrand: 'Adidas',
        competitorSeries: 'Ultraboost 24',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '轻量跑鞋',
        price: 899,
        heatScore: 82,
        tags: ['Boost科技', '轻量', '竞品爆款'],
        materialCategory: '竞品爆款',
        learnable: '科技卖点可视化展示，跑者场景内容',
        statusColor: 'blue',
    },
    {
        id: 'mat_006',
        imageUrl: '/assets/gallery/comp_fluorescent.jpg',
        competitorBrand: 'On',
        competitorSeries: 'Cloudsurfer 7',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '轻量跑鞋',
        price: 799,
        heatScore: 76,
        tags: ['荧光色', '颜色参考', '小批量测试'],
        materialCategory: '颜色参考',
        learnable: '荧光色涂层工艺，可持续材料标注方式',
        riskPoint: '颜色趋势尚未验证大众接受度',
        statusColor: 'orange',
    },
    {
        id: 'mat_007',
        imageUrl: '/assets/gallery/comp_recycle.jpg',
        competitorBrand: 'Allbirds',
        competitorSeries: 'Tree Dasher 2',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '轻量休闲跑',
        price: 599,
        heatScore: 71,
        tags: ['可持续', '再生材料', '功能卖点'],
        materialCategory: '功能卖点',
        learnable: '再生材料鞋面展示，碳足迹认证标注',
        statusColor: 'purple',
    },
    {
        id: 'mat_008',
        imageUrl: '/assets/gallery/comp_luxury_collab.jpg',
        competitorBrand: 'Adidas',
        competitorSeries: 'Samba × Luxury 联名',
        year: 2026,
        season: 'SS',
        category: '休闲鞋',
        shoeType: '板鞋',
        price: 1499,
        heatScore: 62,
        tags: ['联名', '高价格带', '风险趋势'],
        materialCategory: '风险趋势',
        learnable: '联名包装形式参考（不建议直接跟进产品方向）',
        riskPoint: '复购率仅 12%，溢价消费者非本品核心人群',
        statusColor: 'red',
    },
    {
        id: 'mat_009',
        imageUrl: '/assets/gallery/comp_carbon_plate.jpg',
        competitorBrand: 'Nike',
        competitorSeries: 'Vaporfly 3',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '碳板竞速',
        price: 1199,
        heatScore: 86,
        tags: ['碳板', '竞速', '设计参考'],
        materialCategory: '设计参考',
        learnable: '碳板外露设计语言，克重卖点展示',
        riskPoint: '专利壁垒高，不建议直接仿制结构',
        statusColor: 'purple',
    },
    {
        id: 'mat_010',
        imageUrl: '/assets/gallery/comp_trail_material.jpg',
        competitorBrand: 'Merrell',
        competitorSeries: 'Moab Speed',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '越野跑鞋',
        price: 499,
        heatScore: 68,
        tags: ['户外', '防水', '材质参考'],
        materialCategory: '材质参考',
        learnable: 'TPU 骨架 + 防水鞋面工艺，大底纹路设计',
        statusColor: 'blue',
    },
    {
        id: 'mat_011',
        imageUrl: '/assets/gallery/comp_nb_327.jpg',
        competitorBrand: 'New Balance',
        competitorSeries: '327',
        year: 2026,
        season: 'SS',
        category: '休闲鞋',
        shoeType: '低帮休闲鞋',
        price: 399,
        heatScore: 79,
        tags: ['复古', '价格带机会', '板鞋'],
        materialCategory: '价格带机会',
        learnable: '复古跑鞋廓形，N字侧条设计',
        statusColor: 'green',
    },
    {
        id: 'mat_012',
        imageUrl: '/assets/gallery/comp_reebok_nano.jpg',
        competitorBrand: 'Reebok',
        competitorSeries: 'Nano X4',
        year: 2026,
        season: 'SS',
        category: '训练鞋',
        shoeType: '综合训练鞋',
        price: 499,
        heatScore: 74,
        tags: ['训练', '功能卖点', '竞品爆款'],
        materialCategory: '功能卖点',
        learnable: '大底功能分区设计，训练场景内容策略',
        statusColor: 'blue',
    },
    // 折叠后的补充素材
    {
        id: 'mat_013',
        imageUrl: '/assets/gallery/comp_asics_gel.jpg',
        competitorBrand: 'Asics',
        competitorSeries: 'Gel-Nimbus 26',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '缓震跑鞋',
        price: 799,
        heatScore: 72,
        tags: ['缓震', 'Gel科技'],
        materialCategory: '设计参考',
        learnable: 'Gel缓震展示方式，日系配色系统',
        statusColor: 'blue',
    },
    {
        id: 'mat_014',
        imageUrl: '/assets/gallery/comp_under_armour.jpg',
        competitorBrand: 'Under Armour',
        competitorSeries: 'HOVR Phantom',
        year: 2026,
        season: 'SS',
        category: '跑步鞋',
        shoeType: '日常跑鞋',
        price: 599,
        heatScore: 65,
        tags: ['HOVR', '科技感'],
        materialCategory: '设计参考',
        learnable: '能量反馈科技卖点展示',
        statusColor: 'gray',
    },
];

// ─── Mock Related Module Links ────────────────────────────────────────────────
const MOCK_RELATED_LINKS: CompetitorTrendRelatedModuleLink[] = [
    {
        moduleId: 'consumer',
        moduleName: '消费者画像',
        relationship: '验证趋势对应人群和价格接受度',
        icon: '👥',
        targetTab: 'consumer',
        ctaLabel: '验证人群机会',
    },
    {
        moduleId: 'category',
        moduleName: '品类运营',
        relationship: '把升量品类和鞋型机会转为品类结构调整',
        icon: '📊',
        targetTab: 'category',
        ctaLabel: '调整品类结构',
    },
    {
        moduleId: 'planning',
        moduleName: '波段企划',
        relationship: '把趋势转为波段主题、主推款和上新节奏',
        icon: '📋',
        targetTab: 'planning',
        ctaLabel: '加入波段企划',
    },
    {
        moduleId: 'otb',
        moduleName: 'OTB预算',
        relationship: '把趋势机会转为测试款预算或主推款预算',
        icon: '💰',
        targetTab: 'otb',
        ctaLabel: '生成OTB建议',
    },
    {
        moduleId: 'forecast',
        moduleName: '销售预测',
        relationship: '验证趋势对应销售潜力',
        icon: '📈',
        targetTab: 'forecast',
        ctaLabel: '查看销售潜力',
    },
    {
        moduleId: 'design',
        moduleName: '设计计划',
        relationship: '生成趋势Brief、竞品对标Brief、设计灵感和开发任务',
        icon: '🎨',
        targetTab: 'design',
        ctaLabel: '加入设计灵感池',
    },
    {
        moduleId: 'inventory',
        moduleName: '库存健康',
        relationship: '避免已有高库存品类继续跟进竞品趋势',
        icon: '📦',
        targetTab: 'inventory',
        ctaLabel: '查看库存风险',
    },
    {
        moduleId: 'profit-loss',
        moduleName: '损益',
        relationship: '评估趋势价格带、毛利和折扣风险',
        icon: '💹',
        targetTab: 'profit-loss',
        ctaLabel: '评估毛利影响',
    },
];

// ─── Hook ─────────────────────────────────────────────────────────────────────
export interface CompetitorTrendData {
    kpis: CompetitorTrendKpi[];
    decisionSummary: TrendDecisionSummary;
    actions: TrendAction[];
    epicRadars: EpicCompetitorRadar[];
    risingTrends: RisingCategoryTrend[];
    designDnaList: CompetitorDesignDna[];
    launchCalendar: CompetitorLaunchCalendarItem[];
    gapAnalysis: CompetitorGapAnalysisItem[];
    planningRecs: TrendPlanningRecommendation[];
    materials: CompetitorMaterialItem[];
    relatedLinks: CompetitorTrendRelatedModuleLink[];
    // Filter options
    brandOptions: string[];
    competitorBrandOptions: string[];
    categoryOptions: string[];
    shoeTypeOptions: string[];
    priceBandOptions: string[];
    channelOptions: string[];
    waveOptions: string[];
}

export function useCompetitorTrendData(filters: Partial<{
    competitorBrand: string;
    category: string;
    shoeType: string;
    priceBand: string;
    heatLevel: string;
}>): CompetitorTrendData {
    const filteredActions = useMemo(() => {
        return MOCK_ACTIONS.filter((action) => {
            if (filters.category && filters.category !== 'all' && !action.recommendedCategory.includes(filters.category)) return false;
            if (filters.shoeType && filters.shoeType !== 'all' && !action.recommendedShoeType.includes(filters.shoeType)) return false;
            if (filters.priceBand && filters.priceBand !== 'all' && action.recommendedPriceBand !== filters.priceBand) return false;
            return true;
        });
    }, [filters.category, filters.shoeType, filters.priceBand]);

    const filteredMaterials = useMemo(() => {
        return MOCK_MATERIALS.filter((mat) => {
            if (filters.competitorBrand && filters.competitorBrand !== 'all' && mat.competitorBrand !== filters.competitorBrand) return false;
            if (filters.category && filters.category !== 'all' && mat.category !== filters.category) return false;
            return true;
        });
    }, [filters.competitorBrand, filters.category]);

    const filteredRisingTrends = useMemo(() => {
        return MOCK_RISING_TRENDS.filter((trend) => {
            if (filters.category && filters.category !== 'all' && trend.category !== filters.category) return false;
            if (filters.shoeType && filters.shoeType !== 'all' && trend.shoeType !== filters.shoeType) return false;
            return true;
        });
    }, [filters.category, filters.shoeType]);

    const filteredEpicRadars = useMemo(() => {
        return MOCK_EPIC_RADARS.filter((radar) => {
            if (filters.competitorBrand && filters.competitorBrand !== 'all' && radar.competitorBrand !== filters.competitorBrand) return false;
            return true;
        });
    }, [filters.competitorBrand]);

    return {
        kpis: MOCK_KPIS,
        decisionSummary: MOCK_DECISION_SUMMARY,
        actions: filteredActions,
        epicRadars: filteredEpicRadars,
        risingTrends: filteredRisingTrends,
        designDnaList: MOCK_DESIGN_DNA,
        launchCalendar: MOCK_LAUNCH_CALENDAR,
        gapAnalysis: MOCK_GAP_ANALYSIS,
        planningRecs: MOCK_PLANNING_RECS,
        materials: filteredMaterials,
        relatedLinks: MOCK_RELATED_LINKS,
        brandOptions: ['本品牌', 'BrandX'],
        competitorBrandOptions: ['Nike', 'New Balance', 'Adidas', 'Hoka', 'Salomon', 'Asics', 'On', 'Reebok'],
        categoryOptions: ['跑步鞋', '休闲鞋', '训练鞋', '篮球鞋'],
        shoeTypeOptions: ['厚底老爹鞋', '越野跑鞋', '竞速跑鞋', '综合训练鞋', '板鞋', '低帮休闲鞋'],
        priceBandOptions: ['299-399', '399-599', '599-799', '799+'],
        channelOptions: ['电商', '直营', '加盟', '直播', '专业门店'],
        waveOptions: ['W1', 'W2', 'W3', 'W4'],
    };
}

// re-export mock defaults for use in sub-components
export {
    MOCK_KPIS,
    MOCK_DECISION_SUMMARY,
    MOCK_ACTIONS,
    MOCK_EPIC_RADARS,
    MOCK_RISING_TRENDS,
    MOCK_DESIGN_DNA,
    MOCK_LAUNCH_CALENDAR,
    MOCK_GAP_ANALYSIS,
    MOCK_PLANNING_RECS,
    MOCK_MATERIALS,
    MOCK_RELATED_LINKS,
};
